project:
  type: website
  output-dir: _site

website:
  title: "Si Lab"

  navbar:
    background: light
    search: true

    left:
      - text: Home
        href: index.qmd

      - text: People
        href: people.qmd

      - text: Research
        href: research.qmd

      - text: Publications
        href: publications.qmd

      - text: Contact
        href: contact.qmd

  page-footer:
    center: "© Si Lab"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

