---
title: "Publications"
---


2026


1.	van der Velden, G., B. Kranstauber, A.-J. Haarsma, R. Janssen, M. van Horssen, W. Halfwerk, A. van Meurs, C. Bom, M. Schrama, and **Y, Si**, To rest or to roam: Functional habitat use of an insectivorous bat species during active and resting behavior. Biological Conservation, 2026: p. 111823. [doi] (https://doi.org/10.1016/j.biocon.2026.111823) 
2.	Teitelbaum, C.S., D.J. Prosser, J.T. Ackerman, … **Y, Si**, … S.E.W. De La Cruz, Waterfowl Move Less in Heterogeneous and Human-Populated Landscapes, With Implications for Spread of Avian Influenza Viruses. Ecology Letters, 2026. 29(1): p. e70265. [doi] (https://doi.org/10.1111/ele.70265) 
3.	Gent, J., P.M. van Bodegom, and **Y, Si**, A conceptual framework for the temporal dynamics of spatial environmental heterogeneity–biodiversity relationships. Frontiers in Ecology and Evolution, 2026. Volume 14 - 2026. [doi] (https://doi.org/10.3389/fevo.2026.1731666) 

2025

4.	Yin, S., C. Zhang, C.S. Teitelbaum, **Y, Si**, G. Zhang, X. Wang, D. Mao, Z.Y.X. Huang, W. Frederik de Boer, J. Takekawa, D.J. Prosser, and X. Xiao, Landscape changes elevate the risk of avian influenza virus diversification and emergence in the East Asian–Australasian Flyway. Proceedings of the National Academy of Sciences, 2025. 122(34): p. e2503427122. [doi] (https://doi.org/10.1073/pnas.2503427122) 

2024

5.	Yin, S., C. Xu, Y. Zhang, W.F. de Boer, T. Mundkur, J. Artois, F.C. Velkers, J.Y. Takekawa, **Y, Si**, H. Tian, G.Z. Han, Y. Chen, H. Chai, L. Cui, and Z.Y.X. Huang, Strong and consistent effects of waterbird composition on HPAI H5 occurrences across Europe. Ecol Appl, 2024: p. e3010. [doi] (https://doi.org/10.1002/eap.3010) 
6.	Xu, F., W. Wu, J. Wei, Q. Xin, B. Wielstra, F.A.L. Sorte, Z. Ma, G. Lei, J. Lei, W. Wu, Y. Yang, P. Gong, B. Xu, and **Y, Si**, Migratory herbivorous waterfowl track multiple resource waves during spring migration. Proceedings of the Royal Society B-Biological Sciences, 2024: p. 20241448. [doi] (https://doi.org/10.1101/2023.04.14.536842) 
7.	Wei, J., F. Xu, E.F. Cole, B.C. Sheldon, W.F. de Boer, B. Wielstra, H. Fu, P. Gong, and **Y, Si**, Spatially heterogeneous shifts in vegetation phenology induced by climate change threaten the integrity of the avian migration network. Global Change Biology, 2024. 30(1): p. e17148. [doi] (https://doi.org/10.1111/gcb.17148) 
8.	Wang, Y., Z. Pan, **Y, Si**, L. Wen, and Y. Guo, Subadult movements contribute to population level migratory connectivity. Animal Behaviour, 2024. 215: p. 143-152. [doi] (https://doi.org/10.1016/j.anbehav.2024.07.007) 

2022

9.	Zhang, L., X. Wan, R. Shi, P. Gong, and **Y, Si**, Comparing spatial patterns of 11 common cancers in Mainland China. BMC Public Health, 2022. 22(1): p. 1551. [doi] (https://doi.org/10.1186/s12889-022-13926-y) 
10.	Hou, S., R. Yang, Y. Cao, Z. Zhao, Q. Peng, H. Wang, and **Y, Si**, A framework for identifying bird conservation priority areas in croplands at national level. Journal of Environmental Management, 2022. 324: p. 116330. [doi] (https://doi.org/10.1016/j.jenvman.2022.116330) 

2021

11.	Zhang, T., B. Tian, D. Sengupta, L. Zhang, and **Y, Si**, Global offshore wind turbine dataset. Scientific Data, 2021. 8(1): p. 191. [doi] (https://doi.org/10.1038/s41597-021-00982-z) 
12.	Yin, S., Y. Xu, N. Batbayar, J.Y. Takekawa, **Y, Si**, D.J. Prosser, S.H. Newman, H.H.T. Prins, and W.F. De Boer, Do contrasting patterns of migration movements and disease outbreaks between congeneric waterfowl species reflect differing immunity? Geospatial Health, 2021. 16(1). [doi] (https://doi.org/10.4081/gh.2021.909) 
13.	Xu, Y., M. Kieboom, R.J.A. van Lammeren, **Y, Si**, and W.F. de Boer, Indicators of site loss from a migration network: anthropogenic factors influence waterfowl movement patterns at stopover sites. Global Ecology and Conservation, 2021. 25: p. e01435. [doi] (https://doi.org/10.1016/j.gecco.2020.e01435) 
14.	**Si, Y.**, F. Xu, J. Wei, L. Zhang, N. Murray, R. Yang, K. Ma, and P. Gong, A systematic network-based migratory bird monitoring and protection system is needed in China. Science Bulletin, 2021. 66(10): p. 955-957. [doi] (https://doi.org/10.1016/j.scib.2021.01.033) 
15.	Gao, B., P. Gong, W. Zhang, J. Yang, and **Y, Si**, Multiscale effects of habitat and surrounding matrices on waterbird diversity in the Yangtze River Floodplain. Landscape Ecology, 2021. 36: p. 179–190. [doi] (https://doi.org/10.1007/s10980-020-01131-4) 

2020

16.	Yin, S., H.J. de Knegt, M.C.M. de Jong, **Y, Si**, H.H.T. Prins, Z.Y.X. Huang, and W.F. de Boer, Effects of migration network configuration and migration synchrony on infection prevalence in geese. Journal of Theoretical Biology, 2020. 502: p. 110315. [doi] (https://doi.org/10.1016/j.jtbi.2020.110315) 
17.	Xu, Y., **Y, Si**, J. Takekawa, Q. Liu, H.H.T. Prins, S. Yin, D.J. Prosser, P. Gong, and W.F. de Boer, A network approach to prioritize conservation efforts for migratory birds. Conservation Biology, 2020. 34(2): p. 416-426. [doi] (https://doi.org/10.1111/cobi.13383) 
18.	**Si, Y.**, J. Wei, W. Wu, W. Zhang, L. Hou, L. Yu, and B. Wielstra, Reducing human pressure on farmland could rescue China’s declining wintering geese. Movement Ecology, 2020. 8(1): p. 35. [doi] (https://doi.org/10.1186/s40462-020-00220-y) 

2019

19.	Xu, Y., **Y, Si**, S. Yin, W. Zhang, M. Grishchenko, H.H.T. Prins, P. Gong, and W.F. de Boer, Species-dependent effects of habitat degradation in relation to seasonal distribution of migratory waterfowl in the East Asian–Australasian Flyway. Landscape Ecology, 2019. 34(2): p. 243-257. [doi] (https://doi.org/10.1007/s10980-018-00767-7) 
20.	Xu, Y., Y. **Si, Y.** Wang, Y. Zhang, H.H.T. Prins, L. Cao, and W.F. de Boer, Loss of functional connectivity in migration networks induces population decline in migratory birds. Ecological Applications, 2019. 29(7): p. e01960. [doi] (https://doi.org/10.1002/eap.1960) 
21.	Xu, F. and **Y, Si**, The frost wave hypothesis: How the environment drives autumn departure of migratory waterfowl. Ecological Indicators, 2019. 101: p. 1018-1025. [doi] (https://doi.org/10.1016/j.ecolind.2019.02.024) 
22.	Wei, J., Q. Xin, L. Ji, P. Gong, and **Y, Si**, Improved satellite-derived identification of spatiotemporal foraging area for herbivorous waterfowl. Ecological Indicators, 2019. 99: p. 83-90. [doi] (https://doi.org/10.1016/j.ecolind.2018.12.016) 
23.	Lv, Z., J. Yang, B. Wielstra, J. Wei, F. Xu, and **Y, Si**, Prioritizing Green Spaces for Biodiversity Conservation in Beijing Based on Habitat Network Connectivity. Sustainability, 2019. 11(7). [doi] (https://doi.org/10.3390/su11072042) 
24.	Huang, Z.Y.X., C. Xu, F. van Langevelde, Y. Ma, T. Langendoen, T. Mundkur, **Y, Si**, H. Tian, R.H.S. Kraus, M. Gilbert, G.-Z. Han, X. Ji, H.H.T. Prins, and W.F. de Boer, Contrasting effects of host species and phylogenetic diversity on the occurrence of HPAI H5N1 in European wild birds. Journal of Animal Ecology, 2019. 88: p. 1044-1053. [doi] (https://doi.org/10.1111/1365-2656.12997) 

2018

25.	Zhang, W., X. Li, L. Yu, and **Y, Si**, Multi-scale habitat selection by two declining East Asian waterfowl species at their core spring stopover area. Ecological Indicators, 2018. 87: p. 127-135. [doi] (https://doi.org/10.1016/j.ecolind.2017.12.035) 
26.	Wielstra, B., D. Canestrelli, M. Cvijanović, M. Denoël, A. Fijarczyk, D. Jablonski, M. Liana, B. Naumov, K. Olgun, M. Pabijan, A. Pezzarossa, G. Popgeorgiev, D. Salvi, **Y, Si**, N. Sillero, K. Sotiropoulos, P. Zieliński, and W. Babik, The distributions of the six species constituting the smooth newt species complex (Lissotriton vulgaris sensu lato and L. montandoni) – an addition to the New Atlas of Amphibians and Reptiles of Europe. Amphibia-Reptilia, 2018. 39(2): p. 252-259. [doi] (https://doi.org/10.1163/15685381-17000128) 
27.	**Si, Y.**, Y. Xu, F. Xu, X. Li, W. Zhang, B. Wielstra, J. Wei, G. Liu, H. Luo, J. Takekawa, S. Balachandran, T. Zhang, W.F.d. Boer, H.H.T. Prins, and P. Gong, Spring migration patterns, habitat use and stopover site protection status for two declining waterfowl species wintering in China as revealed by satellite tracking. Ecology and Evolution, 2018. 8: p. 6280-6289. [doi] (https://doi.org/10.1002/ece3.4174) 
28.	Liu, X., L. Yu, **Y, Si**, C. Zhang, H. Lu, C. Yu, and P. Gong, Identifying patterns and hotspots of global land cover transitions using the ESA CCI Land Cover dataset. Remote Sensing Letters, 2018. 9(10): p. 972-981. [doi] (https://doi.org/10.1080/2150704X.2018.1500070) 

2017

29.	Zhang, H., **Y, Si**, X. Wang, and P. Gong, Environmental Drivers and Predicted Risk of Bacillary Dysentery in Southwest China. International Journal of Environmental Research and Public Health, 2017. 14(7): p. 782. [doi] (https://doi.org/10.3390/ijerph14070782)
30.	Yu, L., X. Li, C. Li, Y. Zhao, Z. Niu, H. Huang, J. Wang, Y. Cheng, H. Lu, **Y, Si**, C. Yu, H. Fu, and P. Gong, Using a global reference sample set and a cropland map for area estimation in China. Science China Earth Sciences, 2017. 60(2): p. 277-285. [doi] (https://doi.org/10.1007/s11430-016-0064-5) 
31.	Yin, S., D. Kleijn, G.J.D.M. Müskens, R.A.M. Fouchier, J.H. Verhagen, P.M. Glazov, **Y, Si**, H.H.T. Prins, and W.F.d. Boer, No evidence that migratory geese disperse avian influenza viruses from breeding to wintering ground. PLOS ONE, 2017. 12(5): p. e0177790. [doi] (https://doi.org/10.1371/journal.pone.0177790) 
32.	Xu, F., G. Liu, and **Y, Si**, Local temperature and El Niño Southern Oscillation influence migration phenology of East Asian migratory waterbirds wintering in Poyang, China. Integrative Zoology, 2017: p. 303-317. [doi] (https://doi.org/10.1111/1749-4877.12248) 
33.	Li, X., **Y, Si**, L. Ji, and P. Gong, Dynamic response of East Asian Greater White-fronted Geese to changes of environment during migration: Use of multi-temporal species distribution model. Ecological Modelling, 2017. 360: p. 70-79. [doi] (https://doi.org/10.1016/j.ecolmodel.2017.06.004) 
34.	Aharon-Rotman, Y., J. McEvoy, Z. Zhaoju, H. Yu, X. Wang, **Y, Si**, Z. Xu, Z. Yuan, W. Jeong, L. Cao, and A.D. Fox, Water level affects availability of optimal feeding habitats for threatened migratory waterbirds. Ecology and Evolution, 2017. 7(23): p. 10440-10450. [doi] (https://doi.org/10.1002/ece3.3566) 

2016

35.	Zhang, H., **Y, Si**, X. Wang, and P. Gong, Patterns of Bacillary Dysentery in China, 2005–2010. International Journal of Environmental Research and Public Health, 2016. 13(2): p. 164. 
36.	Xu, Y., P. Gong, B. Wielstra, and **Y, Si**, Southward autumn migration of waterfowl facilitates cross-continental transmission of the highly pathogenic avian influenza H5N1 virus. Scientific Reports, 2016. 6: p. 30262. [doi] (https://doi.org/10.1038/srep30262) 
37.	Xin, Q.C., P. Gong, A.E. Suyker, and Y.L. Si, Effects of the partitioning of diffuse and direct solar radiation on satellite-based modeling of crop gross primary production. International Journal of Applied Earth Observation and Geoinformation, 2016. 50: p. 51-63. [doi] (https://doi.org/10.1016/j.jag.2016.03.002) 

2015

38.	**Si, Y.**, Q. Xin, H.T. Prins, W. de Boer, and P. Gong, Improving the quantification of waterfowl migration with remote sensing and bird tracking. Science Bulletin, 2015. 60(23): p. 1984-1993. [doi] ([doi] (https://doi.org/10.1007/s11434-015-0930-9) 
39.	**Si, Y.**, Q. Xin, W.F. de Boer, P. Gong, R.C. Ydenberg, and H.H.T. Prins, Do Arctic breeding geese track or overtake a green wave during spring migration? Scientific Reports, 2015. 5: p. 8749. [doi] (https://doi.org/10.1038/srep08749) 
40.	**Si, Y.** and H.H.T. Prins, Climate law: path paved for civil action. Nature, 2015. 523(7561): p. 410. [doi] (https://doi.org/10.1038/523410e) 
41.	Li, X., N. Clinton, **Y, Si**, J. Liao, L. Liang, and P. Gong, Projected impacts of climate change on protected birds and nature reserves in China. Science Bulletin, 2015: p. 1-10. [doi] (https://doi.org/10.1007/s11434-015-0892-y) 

2013

42.	**Si, Y.**, W.F. de Boer, and P. Gong, Different environmental drivers of highly pathogenic avian influenza H5N1 outbreaks in poultry and wild birds. PLoS One, 2013. 8(1): p. e53362. [doi] (https://doi.org/10.1371/journal.pone.0053362) 
43.	Guo, D., H. Zhou, Y. Zou, W. Yin, H. Yu, **Y, Si**, J. Li, Y. Zhou, X. Zhou, and R.J. Magalhaes, Geographical analysis of the distribution and spread of human rabies in china from 2005 to 2011. PLoS One, 2013. 8(8): p. e72352. [doi] (https://doi.org/10.1371/journal.pone.0072352) 

2012

44.	Ullah, S., **Y, Si**, M. Schlerf, A.K. Skidmore, M. Shafique, and I.A. Iqbal, Estimation of grassland biomass and nitrogen using MERIS data. International Journal of Applied Earth Observation and Geoinformation, 2012. 19: p. 196-204. [doi] (https://doi.org/10.1016/j.jag.2012.05.008) 
45.	**Si, Y.**, M. Schlerf, R. Zurita-Milla, A. Skidmore, and T. Wang, Mapping spatio-temporal variation of grassland quantity and quality using MERIS data and the PROSAIL model. Remote Sensing of Environment, 2012. 121: p. 415-425. [doi] (https://doi.org/10.1016/j.rse.2012.02.011) 

2011

46.	**Si, Y.**, A.K. Skidmore, T. Wang, W.F.d. Boer, A.G. Toxopeus, M. Schlerf, M. Oudshoorn, S. Zwerver, H.v.d. Jeugd, K.-M. Exo, and H.H.T. Prins, Distribution of Barnacle Geese Branta leucopsis in relation to food resources, distance to roosts, and the location of refuges. Ardea, 2011. 99: p. 217-226. [doi] (https://doi.org/10.5253/078.099.0212) 

2010

47.	Wang, T., A.K. Skidmore, Z. Zeng, P.S.A. Beck, Y.-L. **Si, Y.**-L. Song, X. Liu, and H.H.T. Prins, Migration patterns of two endangered sympatric species from a remote sensing perspective. Photogrammetric Engeneering & Remote Sensing, 2010. 76: p. 1343-1352. [doi] (https://doi.org/10.14358/PERS.76.12.1343) 
48.	**Si, Y.**, T. Wang, A.K. Skidmore, W.F. de Boer, L. Li, and H.H.T. Prins, Environmental factors influencing the spread of the highly pathogenic avian influenza H5N1 virus in wild birds in Europe. Ecology and Society, 2010. 15(3): p. 26. [doi] (http://dx.doi.org/10.5751/ES-03622-150326) 

2009

49.	**Si, Y.**, A.K. Skidmore, T. Wang, W.F. de Boer, P. Debba, A.G. Toxopeus, L. Li, and H.H. Prins, Spatio-temporal dynamics of global H5N1 outbreaks match bird migration patterns. Geospat Health, 2009. 4(1): p. 65-78. [doi] (https://doi.org/10.4081/gh.2009.211) 

